# Generated by Django 3.2.5 on 2021-07-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210727_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
