# Generated by Django 3.2.5 on 2021-07-24 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='artist', serialize=False, to='accounts.customuser')),
                ('brand_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('web_link', models.URLField(blank=True, max_length=255, null=True)),
                ('zip_code', models.SmallIntegerField()),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('brand_logo', models.ImageField(upload_to='images')),
                ('company_documents', models.FileField(upload_to='images')),
                ('facebook_link', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=255, null=True)),
                ('LinkedIn_link', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
